class_name VSCoin
extends Node2D
## Gold-coin pickup — the seed of Vampire Survivors' "coins" meta-currency. Dropped from
## shattering a candelabra (see VSRun.drop_candelabra_bonus) in one of three value tiers, it
## magnetizes toward a nearby player like food/gems and increments the run's `gold` counter on
## pickup. The lone exception is the KILL_DROP tier — a single coin a kill coughs up only while
## a Gold Fever is active (VSRun._maybe_drop_gold_fever_coin). Grants no XP or HP; it exists to
## bank currency for a future between-run meta-progression.


## What spawned this coin, which sets how much it tops up an active Gold Fever on collect
## (see _collect and Gilded_Clover.md) — it does NOT affect the banked gold, which is `value`.
## The three light-source pickup tiers (Light_source.md's Gold Coin / Coin Bag / Rich Coin
## Bag) extend by 0.5/5/10s; KILL_DROP is a coin coughed up by a kill *during* a fever, which
## the wiki extends by only 0.01s so a busy fight can't pin the timer to full. Defaults to the
## base GOLD_COIN pickup tier.
enum Tier { GOLD_COIN, COIN_BAG, RICH_COIN_BAG, KILL_DROP }

# Seconds each tier tops an active Gold Fever back up by on collect (see fever_extension_seconds).
static var FEVER_EXT_GOLD_COIN := BalanceData.get_value("coin_fever_ext_gold_coin", 0.5)
static var FEVER_EXT_COIN_BAG := BalanceData.get_value("coin_fever_ext_coin_bag", 5.0)
static var FEVER_EXT_RICH_COIN_BAG := BalanceData.get_value("coin_fever_ext_rich_coin_bag", 10.0)
static var FEVER_EXT_KILL_DROP := BalanceData.get_value("coin_fever_ext_kill_drop", 0.01)

var run: VSRun
var value: int = int(BalanceData.get_value("coin_value", 1.0))                # gold banked on pickup
var tier: Tier = Tier.GOLD_COIN
var _t := 0.0                 # bob timer

## Seconds this coin adds to an active Gold Fever when collected (Gilded_Clover.md: Gold Coin
## 0.5s, Coin Bag 5s, Rich Coin Bag 10s, and coins generated by killing enemies during the
## fever only 0.01s; the run clamps the total to the full 10s).
func fever_extension_seconds() -> float:
	match tier:
		Tier.COIN_BAG:
			return FEVER_EXT_COIN_BAG
		Tier.RICH_COIN_BAG:
			return FEVER_EXT_RICH_COIN_BAG
		Tier.KILL_DROP:
			return FEVER_EXT_KILL_DROP
		_:
			return FEVER_EXT_GOLD_COIN

func _ready() -> void:
	add_to_group("coins")
	var sprite := Sprite2D.new()
	sprite.texture = load("res://art/gold_coin.png")
	VSPickup.apply(sprite)
	add_child(sprite)

func _process(delta: float) -> void:
	if run == null or run.phase != "playing" or run.player == null or not is_instance_valid(run.player):
		return
	# Gentle bob so it reads as a live, grabbable pickup rather than debris.
	_t += delta
	scale = Vector2.ONE * (1.0 + 0.06 * sin(_t * 4.0))
	var pl := run.player
	var to := pl.position - position
	var d := to.length()
	# Attractorb passive widens the base magnet radius so coins fly in from farther.
	if d < VSPickup.MAGNET_RADIUS * run.pickup_range_mult and d > 0.5:
		position += to / d * VSPickup.MAGNET_SPEED * delta
	if d < VSPickup.GRAB_RADIUS + VSPlayer.PICKUP_RADIUS:
		_collect()

func _collect() -> void:
	run.add_gold(value)
	# Gilded_Clover.md: grabbing a coin while a Gold Fever is running tops its timer back up
	# by the tier's amount (the run caps it at the full 10s), now legible via the HUD's
	# GOLD FEVER countdown bar.
	if run.is_gold_fever_active():
		run.extend_gold_fever(fever_extension_seconds())
	AgentBridge.emit_event("pickup", {"type": "coin", "gold": value})
	var parent := get_parent()
	if parent != null:
		# Gold bloom + "+N" so banking currency reads as a distinct little reward.
		VSPickupFlash.spawn(parent, position, Color(1.0, 0.85, 0.3))
		VSFloatText.spawn(parent, position, "+%d" % value, Color(1.0, 0.85, 0.3))
	queue_free()
